apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-buddy.fullname" . }}
  labels:
    {{- include "cluster-buddy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cluster-buddy.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cluster-buddy.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "cluster-buddy.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "cluster-buddy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/cluster-buddy
          args:
          {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "cluster-buddy.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HELM_CACHE_HOME
              value: /opt/dashboard/helm/cache
            - name: HELM_CONFIG_HOME
              value: /opt/dashboard/helm/config
            - name: HELM_DATA_HOME
              value: /opt/dashboard/helm/data
            - name: DEBUG
              value: {{- ternary " '1'" "" .Values.debug }}
            {{- if .Values.dashboard.namespace }}
            - name: HELM_NAMESPACE
              value: {{ .Values.dashboard.namespace }}
            {{end}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/dashboard/helm
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
        {{- if .Values.dashboard.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "cluster-buddy.fullname" . }}
        {{- else }}
          emptyDir: { }
        {{- end }}

